### ISSUE TITLE
iPhone Safari testing

### ISSUE THREAD

**Issue by char1129** [hoanganhduong/confectionery-website-prototype#3]
See attached photo.

Space between nav and first photo, intentional?

![C7E7C72B-85A1-4C8E-873B-7685AE94A6AA](https://user-images.githubusercontent.com/55107755/70468191-a4c3d180-1a94-11ea-934d-defc99936737.png)

**Comment by hoanganhduong** [comment]
Thanks for providing the screenshot that helps a lot :)). It's not intentional and I'm fixing it.
Thanks :))
